### PR TITLE
Fix minitest deprecation warnings

### PR DESCRIPTION
**Pull request by archanaserver**
In this PR, fix minitest deprecation warnings.

### CODE REVIEW

**Comment by archanaserver** [comment]
@ekohl, I'm not sure if we need this changes. WDYT?

**Comment by archanaserver** [comment]
Sure, also I've updated it. Thanks @ekohl.

**Comment by ekohl** [comment]
I don't see an update. Did you forget to push?

**Comment by archanaserver** [comment]
> I don't see an update. Did you forget to push?

Ah sorry, still working on it.

**Comment by archanaserver** [comment]
@ekohl #51 

Also, I can't see this CI workflow in `theforeman/kafo` but Jenkins is there, do we need this on kafo?

**Comment by ekohl** [comment]
I've merged this with an altered commit message to better reflect what it actually changes.

**Pull request merged**
