### PR TITLE
Fixes #7288 - configure module load path correctly

### PR DESCRIPTION
**Pull request by ares**
@domcleal I'd appreciate if you could look at this since you touched this area in 2dd74a283cd407b98fb1a4cb42bc8a761b11d418

EDIT: the `create` public api was added in 3.5.0 - https://github.com/puppetlabs/puppet/blob/3.5.0/lib/puppet/node/environment.rb#L79

### CODE REVIEW

**Comment by domcleal** [comment]
Looks fine to me.  Does the pwd get returned by settings when looking up the modulepath otherwise, or is it implicitly added somewhere else?

**Comment by ares** [comment]
Settings returns this - `"//modules:/usr/share/puppet/modules"`, maybe it's modified somewhere later. I was unable to identify the exact `Dir.pwd` call, but there are couple of them in puppet source code.

**Comment by domcleal** [comment]
Not sure I can confirm that this would fix anything then, I can't even reproduce it on 3.8.4.

**Comment by ares** [comment]
oh I tested with 3.6, let me test with newer version, I though this was easily reproducible since I've seened it since early versions of kafo

**Comment by ares** [comment]
Closing, it was resolved by https://github.com/theforeman/kafo_parsers/commit/2dd74a283cd407b98fb1a4cb42bc8a761b11d418

**Pull request closed without merging**
