### PR TITLE
Remove the old PuppetModuleParser + update dependencies

### PR DESCRIPTION
**Pull request by ekohl**
Most notably this removes the old PuppetModuleParser which means it can only use the puppet-strings based parser. It also updates the minimum version of puppet-strings to 1.2.0.

Various dependencies are also updated to allow for newer versions.

### CODE REVIEW

**Comment by ekohl** [comment]
Note that this will be needed because I can't get kafo (non kafo_parsers) tests to run with the `PuppetModuleParser` because of circular loading. We no longer need it because it's Puppet 3 and older.

**Comment by ares** [comment]
oh wow! I'm not sure why tests are not running here anymore, but I guess I can just run locally and merge if green. Bumping major version seems as a good idea.

**Comment by ekohl** [comment]
@ares the webhook was kindly installed by @ehelms and now the tests did run. I suspect we should start to expand the matrix to also test with Puppet 5 after this PR is merged.

**Comment by mmoll** [comment]
@ares what's the status here? :point_up:

**Comment by ekohl** [comment]
@ares could you have a look?

**Comment by ares** [comment]
Thanks @ekohl, merging

**Pull request merged**
